baseURL = "https://kuno.kdns.info/"
languageCode = "ja-jp"
title = "横あるき"
copyright = "2015 knokmki612"
theme = "fill-and-stroke"
hasCJKLanguage = true
defaultContentLanguage ="ja"
paginate = "10"

[params]
description = "変なことを書き綴るサイトです。"
images = ["favicons/310x310.png"]

[params.cloudinary]
enable = true
cloudName = "dj66cgnpk"
folder = "blog"

[params.cloudinary.transformations]
article = "t_blog_thumb"
ogp = "t_blog_thumb"

[social]
twitter = "knokmki612"

[permalinks]
blog = "/:year/:month/:filename/"

[taxonomies]
tag = "tags"
archive = "archives"

[blackfriday]
plainIDAnchors = false

[markup.goldmark.renderer]
unsafe = true
